{ config, lib, pkgs, ... }:

let
  cfg = config.programs.guilefetch;

  # --- Nix -> Scheme literal helpers --------------------------------------
  schemeString = s: ''"${lib.escape [ "\\" "\"" ] s}"'';
  schemeList = items: "'(${lib.concatStringsSep " " items})";
  schemeBool = b: if b then "#t" else "#f";

  entryDefinitions = lib.concatStringsSep "\n\n" (lib.mapAttrsToList (name: entry: ''
    (define-entry ${name} ${schemeString entry.label}
      ${if entry.command != null
        then ''(run-command "sh" "-c" ${schemeString entry.command})''
        else entry.body})
  '') cfg.extraEntries);

  configFile = pkgs.writeText "guilefetch-config.scm" ''
    ;;; Generated by modules/guilefetch.nix -- do not edit.

    (set-option! 'accent-color ${schemeString cfg.accentColor})
    (set-option! 'label-color ${schemeString cfg.labelColor})
    (set-option! 'label-width ${toString cfg.labelWidth})
    (set-option! 'gap ${toString cfg.gap})
    (set-option! 'logo-align '${cfg.logoAlign})
    (set-option! 'color? ${schemeBool cfg.color})
    (set-option! 'storage-mounts
                 (list ${lib.concatMapStringsSep " " schemeString cfg.storageMounts}))

    ${lib.optionalString (cfg.logoFile != null)
      "(set-logo-file! ${schemeString (toString cfg.logoFile)})"}

    ${entryDefinitions}

    (set-order! ${schemeList cfg.order})

    ${cfg.extraConfig}
  '';

  package = cfg.package.override { defaultConfig = configFile; };
in
{
  options.programs.guilefetch = {
    enable = lib.mkEnableOption "the guilefetch system information printer";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.callPackage ../pkgs/guilefetch { };
      defaultText = lib.literalExpression "pkgs.callPackage ../pkgs/guilefetch { }";
      description = ''
        The unconfigured guilefetch package.  It must accept a
        `defaultConfig' argument; this module overrides that with the
        config file generated from the options below.
      '';
    };

    order = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "title" "rule" "os" "kernel" "packages" "cpu" "gpu" "ram" "storage"
        "shell" "editor" "terminal" "wm" "gui-shell"
      ];
      description = ''
        Entry names to print, in order.  Unknown names are silently
        skipped, and any entry defined in `extraEntries' or `extraConfig'
        must be listed here to appear.
      '';
    };

    logoFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      example = lib.literalExpression "./logos/seraphim.txt";
      description = "Plain-text file holding the ASCII logo.  Any size.";
    };

    logoAlign = lib.mkOption {
      type = lib.types.enum [ "top" "center" ];
      default = "top";
      description = "Vertical alignment of the shorter of logo and info block.";
    };

    accentColor = lib.mkOption {
      type = lib.types.str;
      default = "1;36";
      description = "ANSI SGR parameters for the title.";
    };

    labelColor = lib.mkOption {
      type = lib.types.str;
      default = "1";
      description = "ANSI SGR parameters for entry labels.";
    };

    labelWidth = lib.mkOption {
      type = lib.types.int;
      default = 10;
      description = "Column width labels are padded to; 0 disables padding.";
    };

    gap = lib.mkOption {
      type = lib.types.int;
      default = 3;
      description = "Spaces between the logo and the information block.";
    };

    color = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Whether to emit ANSI colour escapes.";
    };

    storageMounts = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "/" ];
      example = [ "/" "/mnt/scratch" ];
      description = "Mount points reported by the storage entry.";
    };

    extraEntries = lib.mkOption {
      default = { };
      description = ''
        Additional entries, keyed by the name used in `order'.  Give either
        a shell `command' whose stdout becomes the value, or a `body' of
        raw Scheme evaluated inside the guilefetch module.
      '';
      example = lib.literalExpression ''
        {
          uptime = {
            label = "Uptime";
            command = "uptime -p | sed 's/^up //'";
          };
          generation = {
            label = "Generation";
            body = "(basename (readlink \"/run/current-system\"))";
          };
        }
      '';
      type = lib.types.attrsOf (lib.types.submodule ({ name, config, ... }: {
        options = {
          label = lib.mkOption {
            type = lib.types.str;
            description = "Text printed to the left of the separator.";
          };
          command = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Shell command whose trimmed stdout is the value.";
          };
          body = lib.mkOption {
            type = lib.types.nullOr lib.types.lines;
            default = null;
            description = ''
              Scheme expression returning a string, #f to skip the entry, or
              a list of (label . value) pairs for multi-line entries.
            '';
          };
        };
        config = {
          _module.args.entryName = name;
        };
      }));
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = ''
        Scheme appended verbatim to the generated config, after `set-order!'.
        Use it to redefine a built-in entry or set options this module does
        not expose.  Remember that `''' is Nix's escape sequence inside
        indented strings.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = lib.mapAttrsToList (name: entry: {
      assertion = (entry.command == null) != (entry.body == null);
      message = "programs.guilefetch.extraEntries.${name}: set exactly one of `command' or `body'.";
    }) cfg.extraEntries;

    environment.systemPackages = [ package ];
  };
}
