keys:
  - &seraphim age1scdkfhmmrnzy3vemdqw2wv4dz4ympm5mrfcl6weyt5af2u44rfvsxf0asj
  - &ainsoph age1u38ynlvyhl3d543rmfhnpm7fe0jp70r4rl2lc8xqtanen2a725msel2w5n
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *seraphim
          - *ainsoph
